### ISSUE TITLE
miss spelled wdiget in battery_level.py line 49

### ISSUE THREAD

**Issue by erdo100** [usini/headphones_battery#1]
In the the file battery_level.py,
in function update_battery_level 
in line 49
following correction can be done: **wdiget** to **widget**.

wrong:
`self.widget.tooltip["text"] = self.wdiget._["Access denied"]`
correct:
`self.widget.tooltip["text"] = self.widget._["Access denied"]`

Thanks for the code, trying to learn bleak with tkinter.
My first activity here.

**Comment by remisarrailh** [comment]
Thanks, I fixed it.
